import 'package:quran_emufassir/app/constant/api.dart';
import 'package:quran_emufassir/app/data/models/chatbot.dart';

List<Chatbot> listChatbot = [
  Chatbot(
    title: "Chatbot Al-Qur'an",
    desc: "Sumber jawaban diambil dari\nAyat Al-Qur'an dan Terjemahan",
    image: 'assets/images/Quran.png',
    endpoint: "${baseUrlApiChatQuran}alquran-prompt",
    appBar: "Al Qur'an",
  ),
  Chatbot(
    title: "Chatbot Al-Azhar",
    desc: "Sumber jawaban diambil dari\nTafsir Al-Azhar",
    image: 'assets/images/Quran.png',
    endpoint: "${baseUrlApiChatQuran}al-azhar-prompt",
    appBar: "Al-Azhar",
  ),
  Chatbot(
    title: "Chatbot Al-Jalalain",
    desc: "Sumber jawaban diambil dari\nTafsir Al-Jalalain",
    image: 'assets/images/Quran.png',
    endpoint: "${baseUrlApiChatQuran}al-jalalain",
    appBar: "Al-Jalalain",
  ),
  Chatbot(
    title: "Chatbot Ibnu Katsir",
    desc: "Sumber jawaban diambil dari\nTafsir Ibnu Katsir",
    image: 'assets/images/Quran.png',
    endpoint: "${baseUrlApiChatQuran}ibn-kathir",
    appBar: "Ibnu Katsir",
  ),
  Chatbot(
    title: "Chatbot 9 Kitab Hadits",
    desc: "Sumber jawaban diambil dari\n9 Kitab Hadits",
    image: "assets/images/Quran.png",
    endpoint: "${baseUrlApiChatHadits}9_Kitab_Hadits",
    appBar: "9 Kitab Hadits",
  ),
  Chatbot(
    title: "Chatbot Hadits Musnad Ahmad",
    desc: "Sumber jawaban diambil dari\nHadits Musnad Ahmad",
    image: "assets/images/Quran.png",
    endpoint: "${baseUrlApiChatHadits}Musnad_Ahmad",
    appBar: "Musnad Ahmad",
  ),
  Chatbot(
    title: "Chatbot Hadits Sunan Darimi",
    desc: "Sumber jawaban diambil dari\nHadits Sunan Darimi",
    image: "assets/images/Quran.png",
    endpoint: "${baseUrlApiChatHadits}Sunan_Darimi",
    appBar: "Sunan Darimi",
  ),
  Chatbot(
    title: "Chatbot Hadits Muwatha Malik",
    desc: "Sumber jawaban diambil dari\nHadits Muwatha Malik",
    image: "assets/images/Quran.png",
    endpoint: "${baseUrlApiChatHadits}Muwatha_Malik",
    appBar: "Muwatha Malik",
  ),
  Chatbot(
    title: "Chatbot Hadits Shahih Bukhari",
    desc: "Sumber jawaban diambil dari\nHadits Shahih Bukhari",
    image: "assets/images/Quran.png",
    endpoint: "${baseUrlApiChatHadits}Shahih_Bukhari",
    appBar: "Shahih Bukhari",
  ),
  Chatbot(
    title: "Chatbot Hadits Shahih Muslim",
    desc: "Sumber jawaban diambil dari\nHadits Shahih Muslim",
    image: "assets/images/Quran.png",
    endpoint: "${baseUrlApiChatHadits}Shahih_Muslim",
    appBar: "Shahih Muslim",
  ),
  Chatbot(
    title: "Chatbot Hadits Sunan Abu Daud",
    desc: "Sumber jawaban diambil dari\nHadits Sunan Abu Daud",
    image: "assets/images/Quran.png",
    endpoint: "${baseUrlApiChatHadits}Sunan_Abu_Daud",
    appBar: "Sunan Abu Daud",
  ),
  Chatbot(
    title: "Chatbot Hadits Sunan Ibnu Majah",
    desc: "Sumber jawaban diambil dari\nHadits Sunan Ibnu Majah",
    image: "assets/images/Quran.png",
    endpoint: "${baseUrlApiChatHadits}Sunan_Ibnu_Majah",
    appBar: "Sunan Ibnu Majah",
  ),
  Chatbot(
    title: "Chatbot Hadits Sunan Nasai",
    desc: "Sumber jawaban diambil dari\nHadits Sunan Nasai",
    image: "assets/images/Quran.png",
    endpoint: "${baseUrlApiChatHadits}Sunan_Nasai",
    appBar: "Sunan Nasai",
  ),
  Chatbot(
    title: "Chatbot Hadits Sunan Tirmidzi",
    desc: "Sumber jawaban diambil dari\nHadits Sunan Tirmidzi",
    image: "assets/images/Quran.png",
    endpoint: "${baseUrlApiChatHadits}Sunan_Tirmidzi",
    appBar: "Sunan Tirmidzi",
  ),
];
