name: quranapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: 0.13.5
  lottie: 2.2.0
  just_audio: 0.9.34
  get_storage: 2.1.1
  flutter_html: ^3.0.0-alpha.6
  sqflite: 2.2.4+1
  path_provider: 2.0.14
  share_plus: 7.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lotties/
    - assets/images/
  uses-material-design: true

